#!/usr/bin/env python3
"""Pull named function definitions out of a C file, by brace matching.

The renderer differential tests compare the live code in
src/amiga/render_soft.c against frozen copies of what it replaced.  Rather
than duplicating the live code here - which would rot the moment anyone edits
it - this lifts the functions straight out of the real source.

Fails loudly if a function cannot be found or its braces do not balance, so a
rename shows up as a build error rather than as a silently passing test.
"""

import re
import sys

# In dependency order: helpers first, then the functions under test.
WANTED = [
    "fxround",
    "fxwrap",
    "fdiv",
    "cdiv",
    "rdivp",
    "draw_span",
    "draw_upright_quad",
    "softtri",
    "R_DrawFloorSprite",
]


def find_definition(lines, name):
    """Return (start, end) line indices of `name`'s definition, inclusive."""
    # The definition's first line has the name followed by '(' and is not a
    # call (column 0) and not a prototype (it or a later line opens a brace
    # before any ';').
    pat = re.compile(r"^(?:static\s+)?[A-Za-z_][A-Za-z0-9_ \t*]*\b"
                     + re.escape(name) + r"\s*\(")
    for i, line in enumerate(lines):
        if not pat.match(line):
            continue
        # Walk forward to the '{' that opens the body, bailing on a ';' first
        # (that would be a prototype, not a definition).
        j, opened = i, False
        while j < len(lines) and j < i + 12:
            if "{" in lines[j]:
                opened = True
                break
            if ";" in lines[j]:
                break
            j += 1
        if not opened:
            continue
        # Brace match from there.
        depth = 0
        for k in range(j, len(lines)):
            depth += lines[k].count("{") - lines[k].count("}")
            if depth == 0:
                return i, k
        raise SystemExit("extract.py: unbalanced braces in %s" % name)
    return None


def main():
    if len(sys.argv) != 3:
        raise SystemExit("usage: extract.py <source.c> <out.inc>")
    src, out = sys.argv[1], sys.argv[2]
    lines = open(src).read().split("\n")

    chunks = ["/* Generated by tools/rendertest/extract.py - do not edit. */",
              "/* Lifted verbatim from %s */" % src, ""]
    missing = []
    for name in WANTED:
        span = find_definition(lines, name)
        if span is None:
            missing.append(name)
            continue
        chunks.append("\n".join(lines[span[0]:span[1] + 1]))
        chunks.append("")

    if missing:
        raise SystemExit(
            "extract.py: could not find in %s: %s\n"
            "  The renderer was refactored; update WANTED in this script."
            % (src, ", ".join(missing)))

    open(out, "w").write("\n".join(chunks))
    print("extract.py: lifted %d functions into %s" % (len(WANTED), out))


if __name__ == "__main__":
    main()
