/* Key names, generated to match SDL2's so that lab3d.cfg written on a
   desktop machine loads unchanged on the Amiga and vice versa. */
    { PLK_0,               "0" },
    { PLK_1,               "1" },
    { PLK_2,               "2" },
    { PLK_3,               "3" },
    { PLK_4,               "4" },
    { PLK_5,               "5" },
    { PLK_6,               "6" },
    { PLK_7,               "7" },
    { PLK_8,               "8" },
    { PLK_9,               "9" },
    { PLK_a,               "A" },
    { PLK_AMPERSAND,       "&" },
    { PLK_APPLICATION,     "Application" },
    { PLK_ASTERISK,        "*" },
    { PLK_AT,              "@" },
    { PLK_b,               "B" },
    { PLK_BACKQUOTE,       "`" },
    { PLK_BACKSLASH,       "\\" },
    { PLK_BACKSPACE,       "Backspace" },
    { PLK_c,               "C" },
    { PLK_CAPSLOCK,        "CapsLock" },
    { PLK_CARET,           "^" },
    { PLK_CLEAR,           "Clear" },
    { PLK_COLON,           ":" },
    { PLK_COMMA,           "," },
    { PLK_d,               "D" },
    { PLK_DELETE,          "Delete" },
    { PLK_DOLLAR,          "$" },
    { PLK_DOWN,            "Down" },
    { PLK_e,               "E" },
    { PLK_END,             "End" },
    { PLK_EQUALS,          "=" },
    { PLK_ESCAPE,          "Escape" },
    { PLK_EXCLAIM,         "!" },
    { PLK_f,               "F" },
    { PLK_F1,              "F1" },
    { PLK_F10,             "F10" },
    { PLK_F11,             "F11" },
    { PLK_F12,             "F12" },
    { PLK_F13,             "F13" },
    { PLK_F14,             "F14" },
    { PLK_F15,             "F15" },
    { PLK_F2,              "F2" },
    { PLK_F3,              "F3" },
    { PLK_F4,              "F4" },
    { PLK_F5,              "F5" },
    { PLK_F6,              "F6" },
    { PLK_F7,              "F7" },
    { PLK_F8,              "F8" },
    { PLK_F9,              "F9" },
    { PLK_g,               "G" },
    { PLK_GREATER,         ">" },
    { PLK_h,               "H" },
    { PLK_HASH,            "#" },
    { PLK_HOME,            "Home" },
    { PLK_i,               "I" },
    { PLK_INSERT,          "Insert" },
    { PLK_j,               "J" },
    { PLK_k,               "K" },
    { PLK_KP_0,            "Keypad 0" },
    { PLK_KP_1,            "Keypad 1" },
    { PLK_KP_2,            "Keypad 2" },
    { PLK_KP_3,            "Keypad 3" },
    { PLK_KP_4,            "Keypad 4" },
    { PLK_KP_5,            "Keypad 5" },
    { PLK_KP_6,            "Keypad 6" },
    { PLK_KP_7,            "Keypad 7" },
    { PLK_KP_8,            "Keypad 8" },
    { PLK_KP_9,            "Keypad 9" },
    { PLK_KP_DIVIDE,       "Keypad /" },
    { PLK_KP_ENTER,        "Keypad Enter" },
    { PLK_KP_MINUS,        "Keypad -" },
    { PLK_KP_MULTIPLY,     "Keypad *" },
    { PLK_KP_PERIOD,       "Keypad ." },
    { PLK_KP_PLUS,         "Keypad +" },
    { PLK_l,               "L" },
    { PLK_LALT,            "Left Alt" },
    { PLK_LCTRL,           "Left Ctrl" },
    { PLK_LEFT,            "Left" },
    { PLK_LEFTBRACKET,     "[" },
    { PLK_LEFTPAREN,       "(" },
    { PLK_LESS,            "<" },
    { PLK_LGUI,            "Left GUI" },
    { PLK_LSHIFT,          "Left Shift" },
    { PLK_m,               "M" },
    { PLK_MINUS,           "-" },
    { PLK_MODE,            "ModeSwitch" },
    { PLK_n,               "N" },
    { PLK_NUMLOCKCLEAR,    "Numlock" },
    { PLK_o,               "O" },
    { PLK_p,               "P" },
    { PLK_PAGEDOWN,        "PageDown" },
    { PLK_PAGEUP,          "PageUp" },
    { PLK_PAUSE,           "Pause" },
    { PLK_PERIOD,          "." },
    { PLK_PLUS,            "+" },
    { PLK_PRINTSCREEN,     "PrintScreen" },
    { PLK_q,               "Q" },
    { PLK_QUESTION,        "?" },
    { PLK_QUOTE,           "'" },
    { PLK_QUOTEDBL,        "\"" },
    { PLK_r,               "R" },
    { PLK_RALT,            "Right Alt" },
    { PLK_RCTRL,           "Right Ctrl" },
    { PLK_RETURN,          "Return" },
    { PLK_RIGHT,           "Right" },
    { PLK_RIGHTBRACKET,    "]" },
    { PLK_RIGHTPAREN,      ")" },
    { PLK_RSHIFT,          "Right Shift" },
    { PLK_s,               "S" },
    { PLK_SCROLLLOCK,      "ScrollLock" },
    { PLK_SEMICOLON,       ";" },
    { PLK_SLASH,           "/" },
    { PLK_SPACE,           "Space" },
    { PLK_t,               "T" },
    { PLK_TAB,             "Tab" },
    { PLK_u,               "U" },
    { PLK_UNDERSCORE,      "_" },
    { PLK_UNKNOWN,         "" },
    { PLK_UP,              "Up" },
    { PLK_v,               "V" },
    { PLK_w,               "W" },
    { PLK_x,               "X" },
    { PLK_y,               "Y" },
    { PLK_z,               "Z" },
