# Builds the game for multiple platforms and uploads the artifacts
name: Build on multiple platforms

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build_linux:
    name: Build for Linux for x86, x64, ARM, ARM64 and PPC64LE
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Build
      run: ./build-linux.sh

    - name: Upload Linux 386 artifact
      uses: actions/upload-artifact@v4
      with:
        name: Kens-Labyrinth-Linux-386
        path: dist/linux_386/kens-labyrinth-linux-386.tar.gz
        if-no-files-found: error

    - name: Upload Linux AMD64 artifact
      uses: actions/upload-artifact@v4
      with:
        name: Kens-Labyrinth-Linux-AMD64
        path: dist/linux_amd64/kens-labyrinth-linux-amd64.tar.gz
        if-no-files-found: error

    - name: Upload Linux ARMv7 artifact
      uses: actions/upload-artifact@v4
      with:
        name: Kens-Labyrinth-Linux-ARMv7
        path: dist/linux_arm_v7/kens-labyrinth-linux-armv7.tar.gz
        if-no-files-found: error

    - name: Upload Linux ARM64 artifact
      uses: actions/upload-artifact@v4
      with:
        name: Kens-Labyrinth-Linux-ARM64
        path: dist/linux_arm64/kens-labyrinth-linux-arm64.tar.gz
        if-no-files-found: error
    
    - name: Upload Linux PPC64LE artifact
      uses: actions/upload-artifact@v4
      with:
        name: Kens-Labyrinth-Linux-PPC64LE
        path: dist/linux_ppc64le/kens-labyrinth-linux-ppc64le.tar.gz
        if-no-files-found: error

  build_nintendo_switch:
    name: Build for Nintendo Switch
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Build
      run: ./build-switch.sh

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: Kens-Labyrinth-Nintendo-Switch
        path: dist/switch/ken
        if-no-files-found: error

  build_macos:
    name: Build for macOS for Intel and Apple Silicon
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4

    - name: Cache Dependencies
      id: cache-dependencies
      uses: actions/cache@v4
      with:
        path: macports-cache
        key: ${{ runner.os }}-dependencies-${{ hashFiles('**/CMakeLists.txt') }}

    - name: Install dependencies
      if: steps.cache-dependencies.outputs.cache-hit != 'true'
      run: |
        mkdir -p macports-cache
        cd macports-cache
        git clone https://github.com/macports/macports-base.git
        cd macports-base
        ./configure --prefix=${{ github.workspace }}/macports-cache --enable-readline
        make
        sudo make install
        make distclean
        sudo ${{ github.workspace }}/macports-cache/bin/port selfupdate
        echo "macosx_deployment_target 12.4" | sudo tee -a ${{ github.workspace }}/macports-cache/etc/macports/macports.conf > /dev/null
        sudo ${{ github.workspace }}/macports-cache/bin/port install libsdl2 libsdl2_image +universal

    - name: Build
      run: |
        echo ${{ secrets.DEVELOPER_CERTIFICATE }} | base64 --decode > developer_cert.cer
        security import developer_cert.cer -T /usr/bin/codesign
        mkdir -p build
        cd build
        cmake -G Xcode -DCMAKE_BUILD_TYPE=Release -DCMAKE_PREFIX_PATH=${{ github.workspace }}/macports-cache ..
        cmake --build .
        brew install create-dmg
        create-dmg ../dist/macos/Kens-Labyrinth-macOS-Universal.dmg ../dist/macos/

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: Kens-Labyrinth-macOS-Universal
        path: dist/macos/Kens-Labyrinth-macOS-Universal.dmg
        if-no-files-found: error

  build_windows:
    name: Build for Windows for ARM64, x86 and x64
    runs-on: windows-2025

    steps:
    - uses: actions/checkout@v4

    - name: Build for ARM64
      run: |
        mkdir -f build
        cd build
        cmake -A ARM64 ..
        cmake --build . --config Release
        cd ..
        rd -s -q build
        
    - name: Upload Windows ARM64 artifact
      uses: actions/upload-artifact@v4
      with:
        name: Kens-Labyrinth-Windows-ARM64
        path: dist/windows/
        if-no-files-found: error

    - name: Build for x86
      run: |
        mkdir -f build
        cd build
        cmake -A Win32 ..
        cmake --build . --config Release
        cd ..
        rd -s -q build

    - name: Upload Windows x86 artifact
      uses: actions/upload-artifact@v4
      with:
        name: Kens-Labyrinth-Windows-x86
        path: dist/windows/
        if-no-files-found: error

    - name: Build for x64
      run: |
        mkdir -f build
        cd build
        cmake -A x64 ..
        cmake --build . --config Release
        cd ..
        rd -s -q build

    - name: Upload Windows x64 artifact
      uses: actions/upload-artifact@v4
      with:
        name: Kens-Labyrinth-Windows-x64
        path: dist/windows/
        if-no-files-found: error
